[deploy]
bucket = 'cfn-artifacts-crazyfroggg'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'crazyfroggg-project.com'
EnvBackendUrl = 'api.crazyfroggg-project.com'