[deploy]
bucket = 'cfn-artifacts-crazyfroggg'
region = 'us-east-1'
stack_name = 'CrdCluster'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:853114967029:certificate/c4969a87-5a26-44f4-977a-1b8b0a20a365'