[deploy]
bucket = 'cfn-artifacts-crazyfroggg'
region = 'us-east-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'PacurariuIM/aws-bootcamp-cruddur-2023'
ArtifactBucketName = "codepipeline-cruddur-artifacts-crazyfroggg"
BuildSpec = 'backend-flask/buildspec.yml'